site_name: Demo Pages
site_url: https://thearcturus.github.io
theme:
  name: material
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: fr
          name: Français
          build: true
